[package]
name = "mosaic"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }

[addresses]
mosaic = "0x0"

